const $ = (id) => document.getElementById(id);
const STORAGE_KEY = 'necati-cepte-v2';
const defaultState = {
  settings:{partnerName:'Nisa',ownerName:'Necati',relationshipDate:'2025-04-12T00:00',birthDate:'',lastPeriod:'',cycleLength:28,periodLength:5},
  mood:{today:'🥰',history:[]},
  surprises:[{id:1,date:new Date().toISOString().slice(0,10),title:'Bugünün küçük sürprizi',message:'Bir adet uzun sarılma kazandın ❤️',type:'Mesaj'}],
  jar:[
    'gülüşün en sıradan günümü bile güzelleştiriyor','yanında kendim olabiliyorum','birlikte saçmalamak dünyanın en güzel şeyi','zor günlerimde bile yanımda olduğunu hissediyorum','seninle gelecek düşünmek beni mutlu ediyor','sesini duyunca günüm değişiyor','küçük şeyleri bile bizim için özel yapabiliyorsun','sen benim en sevdiğim insansın'
  ],
  memories:[], stories:[
    {id:1,season:1,episode:1,date:'2025-04-12',title:'Biz olduk ❤️',text:'Nisa ve Necati hikâyesinin başladığı gün.',image:''},
    {id:2,season:2,episode:1,date:'2026-06-28',title:'Nişanımız 💍',text:'Hikâyemizin en özel bölümlerinden biri.',image:''}
  ],
  specialDates:[{id:1,title:'Yıldönümümüz',date:'2027-04-12',repeat:'yearly'},{id:2,title:'Nişan yıldönümümüz',date:'2027-06-28',repeat:'yearly'}],
  nights:[], sky:{date:'2025-04-12T21:00',lat:37.0662,lon:37.3833,label:'Gaziantep'}, emergencyLog:[]
};
let state = loadState();
let leafletMap = null; let deferredPrompt;
function clone(x){return JSON.parse(JSON.stringify(x))}
function merge(base, saved){ if(!saved||typeof saved!=='object') return clone(base); const out=clone(base); Object.keys(saved).forEach(k=>{ if(saved[k]&&typeof saved[k]==='object'&&!Array.isArray(saved[k])&&out[k]&&typeof out[k]==='object'&&!Array.isArray(out[k])) out[k]={...out[k],...saved[k]}; else out[k]=saved[k]; }); return out; }
function loadState(){ try{return merge(defaultState,JSON.parse(localStorage.getItem(STORAGE_KEY)||'null'))}catch{return clone(defaultState)} }
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function uid(){return Date.now()+Math.floor(Math.random()*999)}
function fmtDate(v){if(!v)return '—';return new Date(v+'T12:00:00').toLocaleDateString('tr-TR',{day:'2-digit',month:'long',year:'numeric'})}
function today(){return new Date().toISOString().slice(0,10)}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function updateIdentity(){ $('coupleBadge').textContent=`${state.settings.partnerName} ❤️ ${state.settings.ownerName}`; const d=new Date(state.settings.relationshipDate); $('counterSince').textContent=`${d.toLocaleDateString('tr-TR')} tarihinden beri`; document.title=`${state.settings.ownerName} Cepte`; }
function updateCounter(){const start=new Date(state.settings.relationshipDate);let diff=Math.max(0,Date.now()-start);const days=Math.floor(diff/86400000);diff%=86400000;const h=Math.floor(diff/3600000);diff%=3600000;const m=Math.floor(diff/60000);const s=Math.floor((diff%60000)/1000);$('days').textContent=days.toLocaleString('tr-TR');$('hours').textContent=h;$('minutes').textContent=m;$('seconds').textContent=s}
updateIdentity();updateCounter();setInterval(updateCounter,1000);

const messages=[['Nisa’ya küçük bir hatırlatma','Bugün de seni seçiyorum. Yarın da öyle.'],['Necati’den mesaj var 💌','Günün nasıl geçerse geçsin tarafın hep bende.'],['Bugünün görevi','Bir adet sarılma borcun var. Faizi öpücük.'],['Aşk kavanozundan','Seni seviyorum çünkü en sıradan günü bile benim için özel yapabiliyorsun.'],['Mini sürpriz','Bugün sebepsiz yere seni sevdiğimi söylemek istedim. Sebep aramaya gerek yok.']];let messageIndex=0;
$('newMessageBtn').onclick=()=>{messageIndex=(messageIndex+1)%messages.length;$('dailyTitle').textContent=messages[messageIndex][0];$('dailyMessage').textContent=messages[messageIndex][1]};

const moduleNames={mood:'🌸 Nisa Modu',surprise:'🎁 Sürpriz Takvimi',jar:'🫙 Aşk Kavanozu',map:'📍 Anı Haritası',sky:'✨ Bizim Gökyüzümüz',story:'🎬 Hikâyemiz',dates:'💍 Özel Günler',night:'🌙 İyi Geceler',emergency:'🚨 Acil Necati',birthday:'🎂 Doğduğun Gün'};
document.querySelectorAll('.module-card').forEach(b=>b.onclick=()=>openModule(b.dataset.module));
$('backBtn').onclick=showHome;$('homeBtn').onclick=showHome;
function showHome(){if(leafletMap){leafletMap.remove();leafletMap=null}$('homeView').hidden=false;$('moduleView').hidden=true;$('homeBtn').classList.add('active');scrollTo({top:0,behavior:'smooth'})}
function openModule(name){$('homeView').hidden=true;$('moduleView').hidden=false;$('homeBtn').classList.remove('active');$('moduleTitle').textContent=moduleNames[name];renderModule(name);scrollTo({top:0,behavior:'smooth'})}
function renderModule(name){const f={mood:renderMood,surprise:renderSurprise,jar:renderJar,map:renderMap,sky:renderSky,story:renderStory,dates:renderDates,night:renderNight,emergency:renderEmergency,birthday:renderBirthday}[name];f&&f()}

function phaseInfo(){const s=state.settings;if(!s.lastPeriod)return null;const start=new Date(s.lastPeriod+'T12:00:00');const now=new Date();const elapsed=Math.floor((now-start)/86400000);const day=((elapsed%s.cycleLength)+s.cycleLength)%s.cycleLength+1;let phase='Foliküler dönem';if(day<=s.periodLength)phase='Regl dönemi';else if(day>=s.cycleLength-13&&day<=s.cycleLength-11)phase='Tahmini yumurtlama dönemi';else if(day>s.cycleLength-11)phase='Luteal dönem';const next=new Date(start);next.setDate(next.getDate()+Math.ceil(Math.max(0,elapsed+1)/s.cycleLength)*s.cycleLength);if(next<=now)next.setDate(next.getDate()+s.cycleLength);return{day,phase,next}}
const moodTips={'🥰':'Bugün enerji güzel görünüyor. Küçük bir iltifat + sarılma kombosu iyi gider ❤️','🙂':'Sakin ve tatlı bir gün. “Bir şeye ihtiyacın var mı?” sorusu puan kazandırır.','😴':'Nisa yorgun olabilir. Planı hafiflet, dinlenmesine alan aç ve çay/kahve teklif et ☕','😔':'Çözüm sunmadan önce dinle. “Yanındayım” demek bugün daha değerli olabilir.','😡':'Savunmaya geçmeden dinle 😅 Tartışmayı kazanmak yerine birbirinizi anlamaya çalışın; sevdiği küçük bir şeyi düşün.'};
function renderMood(){const p=phaseInfo();$('moduleContent').innerHTML=`<div class="panel"><h3>Bugün Nisa nasıl hissediyor?</h3><div class="mood-grid">${Object.entries({'🥰':'Mutlu','🙂':'İyi','😴':'Yorgun','😔':'Üzgün','😡':'Gergin'}).map(([e,l])=>`<button class="mood-btn ${state.mood.today===e?'active':''}" data-mood="${e}"><strong>${e}</strong>${l}</button>`).join('')}</div><div class="hero-tip" id="moodTip">${moodTips[state.mood.today]}</div></div><div class="panel"><h3>Döngü tahmini</h3>${p?`<div class="stats-grid"><div class="stat-card"><strong>${p.day}. gün</strong><span>Döngü günü</span></div><div class="stat-card"><strong>${p.phase}</strong><span>Tahmini dönem</span></div><div class="stat-card"><strong>${p.next.toLocaleDateString('tr-TR')}</strong><span>Tahmini sonraki başlangıç</span></div></div>`:`<div class="empty">Ayarlar'dan son regl başlangıç tarihini girince tahmin burada görünecek.</div>`}<p class="tiny">Bu bölüm yalnızca kişisel takip ve eğlence amaçlı yaklaşık hesap yapar; tıbbi değerlendirme değildir.</p></div><div class="panel"><h3>Son ruh halleri</h3>${state.mood.history.length?`<div class="cards-list">${state.mood.history.slice(-7).reverse().map(x=>`<div class="surprise-card"><b>${x.mood}</b> ${fmtDate(x.date)}</div>`).join('')}</div>`:`<div class="empty">Henüz kayıt yok.</div>`}</div>`;document.querySelectorAll('[data-mood]').forEach(b=>b.onclick=()=>{state.mood.today=b.dataset.mood;state.mood.history.push({date:today(),mood:b.dataset.mood});save();renderMood();toast('Ruh hali kaydedildi 🌸')})}

function renderSurprise(){$('moduleContent').innerHTML=`<div class="panel"><h3>Yeni sürpriz ekle</h3><div class="form-grid"><label>Tarih<input id="spDate" type="date" value="${today()}"></label><label>Tür<select id="spType"><option>Mesaj</option><option>Görev</option><option>Sürpriz</option><option>Buluşma</option></select></label></div><label>Başlık<input id="spTitle" placeholder="Bugünün kutusu"></label><label>İçerik<textarea id="spMessage" placeholder="Nisa kutuyu açınca ne görsün?"></textarea></label><div class="actions"><button class="primary-btn" id="addSurprise">Takvime ekle 🎁</button></div></div><div class="panel"><h3>Kutular</h3><div class="cards-list">${state.surprises.sort((a,b)=>a.date.localeCompare(b.date)).map(x=>{const locked=x.date>today();return `<div class="surprise-card ${locked?'locked':''}"><div class="row-between"><div><span class="chip">${fmtDate(x.date)} · ${escapeHtml(x.type)}</span><h3>${locked?'🔒 ': '🎁 '}${escapeHtml(x.title)}</h3></div><button class="delete-btn" data-delsp="${x.id}">Sil</button></div><p>${locked?'Bu kutu zamanı gelince açılacak ❤️':escapeHtml(x.message)}</p></div>`}).join('')||'<div class="empty">Henüz sürpriz yok.</div>'}</div></div>`;$('addSurprise').onclick=()=>{const date=$('spDate').value,title=$('spTitle').value.trim(),message=$('spMessage').value.trim();if(!date||!title||!message)return toast('Tarih, başlık ve içerik gerekli');state.surprises.push({id:uid(),date,title,message,type:$('spType').value});save();renderSurprise();toast('Sürpriz eklendi 🎁')};document.querySelectorAll('[data-delsp]').forEach(b=>b.onclick=()=>{state.surprises=state.surprises.filter(x=>x.id!=b.dataset.delsp);save();renderSurprise()})}

function dailyJar(){if(!state.jar.length)return 'Kavanoz şu an boş 💗';const d=new Date();const key=Number(`${d.getFullYear()}${d.getMonth()+1}${d.getDate()}`);return state.jar[key%state.jar.length]}
function renderJar(){$('moduleContent').innerHTML=`<div class="jar-main"><span class="pill">Bugünün kartı 🫙</span><p class="big-quote">“Seni seviyorum çünkü ${escapeHtml(dailyJar())}.”</p></div><div class="panel"><h3>Kavanoza yeni kart ekle</h3><label>Seni seviyorum çünkü...<textarea id="jarText" placeholder="..."></textarea></label><div class="actions"><button id="addJar" class="primary-btn">Kavanoza at ❤️</button></div></div><div class="panel"><h3>Kavanozdaki kartlar (${state.jar.length})</h3><div class="cards-list">${state.jar.map((x,i)=>`<div class="jar-card row-between"><span>${escapeHtml(x)}</span><button class="delete-btn" data-deljar="${i}">Sil</button></div>`).join('')}</div></div>`;$('addJar').onclick=()=>{const v=$('jarText').value.trim();if(!v)return;state.jar.push(v.replace(/^seni seviyorum çünkü\s*/i,''));save();renderJar();toast('Kavanoza eklendi ❤️')};document.querySelectorAll('[data-deljar]').forEach(b=>b.onclick=()=>{state.jar.splice(Number(b.dataset.deljar),1);save();renderJar()})}

function compressImage(file,cb){if(!file)return cb('');const r=new FileReader();r.onload=e=>{const img=new Image();img.onload=()=>{const max=900,scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);cb(c.toDataURL('image/jpeg',.72))};img.src=e.target.result};r.readAsDataURL(file)}
function renderMap(){$('moduleContent').innerHTML=`<div class="panel"><h3>Yeni anı noktası</h3><div class="form-grid"><label>Başlık<input id="memTitle" placeholder="İlk buluşma"></label><label>Tarih<input id="memDate" type="date"></label><label>Enlem<input id="memLat" type="number" step="any" placeholder="37.0662"></label><label>Boylam<input id="memLon" type="number" step="any" placeholder="37.3833"></label></div><label>Not<textarea id="memNote"></textarea></label><label>Fotoğraf (isteğe bağlı)<input id="memPhoto" type="file" accept="image/*"></label><div class="actions"><button class="ghost-btn" id="useLocation">📍 Bulunduğum konumu kullan</button><button class="primary-btn" id="addMemory">Anıyı ekle</button></div></div><div class="panel"><div id="mapBox" class="map-box"></div><p class="tiny">Harita OpenStreetMap verilerini kullanır; harita döşemeleri için internet gerekir.</p></div><div class="memory-grid">${state.memories.map(x=>`<div class="memory-card">${x.image?`<img src="${x.image}" alt="">`:''}<div class="row-between"><div><div class="card-title">${escapeHtml(x.title)}</div><div class="card-meta">${fmtDate(x.date)}</div></div><button class="delete-btn" data-delmem="${x.id}">Sil</button></div><p>${escapeHtml(x.note||'')}</p></div>`).join('')||'<div class="empty">Haritaya ilk anınızı ekleyin ❤️</div>'}</div>`;setTimeout(initLeaflet,0);$('useLocation').onclick=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>{$('memLat').value=p.coords.latitude.toFixed(6);$('memLon').value=p.coords.longitude.toFixed(6);toast('Konum alındı 📍')},()=>toast('Konum izni alınamadı')):toast('Konum desteği yok');$('addMemory').onclick=()=>{const title=$('memTitle').value.trim(),date=$('memDate').value,lat=parseFloat($('memLat').value),lon=parseFloat($('memLon').value),note=$('memNote').value.trim();if(!title||!Number.isFinite(lat)||!Number.isFinite(lon))return toast('Başlık ve geçerli koordinat gerekli');compressImage($('memPhoto').files[0],image=>{state.memories.push({id:uid(),title,date,lat,lon,note,image});try{save()}catch{state.memories[state.memories.length-1].image='';save();toast('Fotoğraf depolama alanına sığmadı, anı fotoğrafsız kaydedildi')}renderMap();toast('Anı haritaya eklendi ❤️')})};document.querySelectorAll('[data-delmem]').forEach(b=>b.onclick=()=>{state.memories=state.memories.filter(x=>x.id!=b.dataset.delmem);save();renderMap()})}
function initLeaflet(){if(!window.L){$('mapBox').innerHTML='<div class="empty">Harita yüklenemedi. İnternet bağlantısını kontrol et.</div>';return}if(leafletMap)leafletMap.remove();const center=state.memories.length?[state.memories[0].lat,state.memories[0].lon]:[37.0662,37.3833];leafletMap=L.map('mapBox').setView(center,state.memories.length?12:10);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(leafletMap);state.memories.forEach(m=>L.marker([m.lat,m.lon]).addTo(leafletMap).bindPopup(`<b>${escapeHtml(m.title)}</b><br>${escapeHtml(m.note||'')}`));setTimeout(()=>leafletMap.invalidateSize(),120)}

const stars=[['Sirius',6.7525,-16.7161,-1.46],['Canopus',6.3992,-52.6957,-.74],['Arcturus',14.261,19.1825,-.05],['Vega',18.6156,38.7837,.03],['Capella',5.2782,45.998,.08],['Rigel',5.2423,-8.2016,.13],['Procyon',7.655,5.225,.34],['Betelgeuse',5.9195,7.407,.42],['Altair',19.8464,8.8683,.77],['Aldebaran',4.5987,16.5093,.86],['Antares',16.4901,-26.432,.96],['Spica',13.4199,-11.1614,.97],['Pollux',7.7553,28.0262,1.14],['Fomalhaut',22.9608,-29.6222,1.16],['Deneb',20.6905,45.2803,1.25],['Regulus',10.1395,11.9672,1.35],['Castor',7.5767,31.8883,1.58],['Bellatrix',5.4189,6.3497,1.64],['Elnath',5.4382,28.6075,1.65],['Alnilam',5.6036,-1.2019,1.69],['Alnitak',5.6793,-1.9426,1.74],['Mirfak',3.4054,49.8612,1.79],['Dubhe',11.0621,61.7508,1.79],['Wezen',7.1399,-26.3932,1.83],['Kaus Australis',18.4029,-34.3846,1.79],['Polaris',2.5303,89.2641,1.98],['Hamal',2.1196,23.4624,2.0],['Diphda',0.7265,-17.9866,2.02],['Mizar',13.3987,54.9254,2.06],['Algol',3.1361,40.9556,2.12]];
function jd(date){return date/86400000+2440587.5}function norm(x){return((x%360)+360)%360}function starAltAz(raH,decD,date,lat,lon){const J=jd(date),T=(J-2451545)/36525,gmst=norm(280.46061837+360.98564736629*(J-2451545)+.000387933*T*T-T*T*T/38710000),lst=norm(gmst+lon),H=(norm(lst-raH*15))*Math.PI/180,dec=decD*Math.PI/180,phi=lat*Math.PI/180;const alt=Math.asin(Math.sin(phi)*Math.sin(dec)+Math.cos(phi)*Math.cos(dec)*Math.cos(H));const az=Math.atan2(-Math.sin(H)*Math.cos(dec),Math.sin(dec)*Math.cos(phi)-Math.cos(dec)*Math.sin(phi)*Math.cos(H));return{alt:alt*180/Math.PI,az:norm(az*180/Math.PI)}}
function renderSky(){$('moduleContent').innerHTML=`<div class="panel"><h3>Özel gecenin gökyüzü</h3><div class="form-grid"><label>Tarih ve saat<input id="skyDate" type="datetime-local" value="${state.sky.date}"></label><label>Yer adı<input id="skyLabel" value="${escapeHtml(state.sky.label)}"></label><label>Enlem<input id="skyLat" type="number" step="any" value="${state.sky.lat}"></label><label>Boylam<input id="skyLon" type="number" step="any" value="${state.sky.lon}"></label></div><div class="actions"><button id="skyHere" class="ghost-btn">📍 Konumumu kullan</button><button id="drawSky" class="primary-btn">Gökyüzünü oluştur ✨</button></div></div><div class="sky-wrap"><canvas id="skyCanvas" class="sky-canvas" width="900" height="900"></canvas></div><p class="tiny">Bu harita seçilmiş parlak yıldızların gerçek astronomik koordinatlarını, seçtiğin tarih/saat ve konuma göre ufuk üstündeki konumlarına dönüştürür. Tüm yıldızları içeren profesyonel gökevi kataloğu değildir.</p>`;$('drawSky').onclick=()=>{state.sky={date:$('skyDate').value,label:$('skyLabel').value,lat:parseFloat($('skyLat').value),lon:parseFloat($('skyLon').value)};save();drawSky()};$('skyHere').onclick=()=>navigator.geolocation&&navigator.geolocation.getCurrentPosition(p=>{$('skyLat').value=p.coords.latitude;$('skyLon').value=p.coords.longitude;toast('Konum alındı ✨')},()=>toast('Konum izni alınamadı'));drawSky()}
function drawSky(){const c=$('skyCanvas');if(!c)return;const ctx=c.getContext('2d'),w=c.width,h=c.height,cx=w/2,cy=h/2,R=w*.44;ctx.fillStyle='#030510';ctx.fillRect(0,0,w,h);const g=ctx.createRadialGradient(cx,cy,0,cx,cy,R);g.addColorStop(0,'#121c42');g.addColorStop(1,'#040612');ctx.fillStyle=g;ctx.beginPath();ctx.arc(cx,cy,R,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.16)';ctx.lineWidth=2;ctx.stroke();ctx.font='22px sans-serif';ctx.fillStyle='rgba(255,255,255,.45)';[['K',0,-R-10],['D',R+10,7],['G',0,R+28],['B',-R-28,7]].forEach(([t,x,y])=>ctx.fillText(t,cx+x-7,cy+y));const date=new Date(state.sky.date),lat=Number(state.sky.lat),lon=Number(state.sky.lon);stars.forEach(([name,ra,dec,mag])=>{const p=starAltAz(ra,dec,date,lat,lon);if(p.alt<=0)return;const rr=R*(1-p.alt/90),a=(p.az-90)*Math.PI/180,x=cx+rr*Math.cos(a),y=cy+rr*Math.sin(a),size=Math.max(2,8-mag*1.6);ctx.beginPath();ctx.fillStyle='#fff';ctx.shadowColor='#a8c7ff';ctx.shadowBlur=12;ctx.arc(x,y,size,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;if(mag<1.4){ctx.font='17px sans-serif';ctx.fillStyle='rgba(255,255,255,.74)';ctx.fillText(name,x+10,y-8)}});ctx.textAlign='center';ctx.font='700 24px sans-serif';ctx.fillStyle='#fff';ctx.fillText(`${state.settings.partnerName} ❤️ ${state.settings.ownerName}`,cx,45);ctx.font='18px sans-serif';ctx.fillStyle='rgba(255,255,255,.65)';ctx.fillText(`${state.sky.label} · ${new Date(state.sky.date).toLocaleString('tr-TR')}`,cx,75);ctx.textAlign='start'}

function renderStory(){$('moduleContent').innerHTML=`<div class="panel"><h3>Yeni bölüm ekle</h3><div class="form-grid"><label>Sezon<input id="stSeason" type="number" min="1" value="1"></label><label>Bölüm<input id="stEpisode" type="number" min="1" value="1"></label><label>Tarih<input id="stDate" type="date"></label><label>Başlık<input id="stTitle" placeholder="Bölüm adı"></label></div><label>Hikâye<textarea id="stText"></textarea></label><label>Fotoğraf<input id="stPhoto" type="file" accept="image/*"></label><div class="actions"><button id="addStory" class="primary-btn">Bölümü yayınla 🎬</button></div></div><div class="story-grid">${[...state.stories].sort((a,b)=>a.season-b.season||a.episode-b.episode).map(x=>`<div class="story-card">${x.image?`<img src="${x.image}">`:''}<span class="chip">Sezon ${x.season} · Bölüm ${x.episode}</span><h3>${escapeHtml(x.title)}</h3><div class="card-meta">${fmtDate(x.date)}</div><p>${escapeHtml(x.text)}</p><button class="delete-btn" data-delstory="${x.id}">Bölümü sil</button></div>`).join('')}</div>`;$('addStory').onclick=()=>{const title=$('stTitle').value.trim(),text=$('stText').value.trim();if(!title||!text)return toast('Başlık ve hikâye gerekli');compressImage($('stPhoto').files[0],image=>{state.stories.push({id:uid(),season:+$('stSeason').value,episode:+$('stEpisode').value,date:$('stDate').value,title,text,image});save();renderStory();toast('Yeni bölüm eklendi 🎬')})};document.querySelectorAll('[data-delstory]').forEach(b=>b.onclick=()=>{state.stories=state.stories.filter(x=>x.id!=b.dataset.delstory);save();renderStory()})}

function daysUntil(dateStr,repeat){const now=new Date();now.setHours(0,0,0,0);let d=new Date(dateStr+'T00:00:00');if(repeat==='yearly'){d.setFullYear(now.getFullYear());if(d<now)d.setFullYear(now.getFullYear()+1)}return Math.ceil((d-now)/86400000)}
function renderDates(){$('moduleContent').innerHTML=`<div class="panel"><h3>Özel gün ekle</h3><div class="form-grid"><label>Adı<input id="dateTitle" placeholder="Yıldönümümüz"></label><label>Tarih<input id="dateValue" type="date"></label><label>Tekrar<select id="dateRepeat"><option value="yearly">Her yıl</option><option value="none">Tek sefer</option></select></label></div><div class="actions"><button id="addDate" class="primary-btn">Ekle 💍</button></div></div><div class="date-grid">${state.specialDates.map(x=>{const d=daysUntil(x.date,x.repeat);return `<div class="date-card"><div class="row-between"><span class="chip">${fmtDate(x.date)}</span><button class="delete-btn" data-deldate="${x.id}">Sil</button></div><h3>${escapeHtml(x.title)}</h3><strong style="font-size:1.6rem">${d===0?'Bugün! ❤️':d>0?`${d} gün kaldı`:`${Math.abs(d)} gün önce`}</strong></div>`}).join('')||'<div class="empty">Özel gün ekleyin.</div>'}</div>`;$('addDate').onclick=()=>{const title=$('dateTitle').value.trim(),date=$('dateValue').value;if(!title||!date)return toast('Başlık ve tarih gerekli');state.specialDates.push({id:uid(),title,date,repeat:$('dateRepeat').value});save();renderDates()};document.querySelectorAll('[data-deldate]').forEach(b=>b.onclick=()=>{state.specialDates=state.specialDates.filter(x=>x.id!=b.dataset.deldate);save();renderDates()})}

function renderNight(){$('moduleContent').innerHTML=`<div class="panel"><h3>İyi geceler mesajı ekle 🌙</h3><label>Tarih<input id="nightDate" type="date" value="${today()}"></label><label>Mesaj<textarea id="nightText" placeholder="iyi geceler aşkım..."></textarea></label><div class="actions"><button id="addNight" class="primary-btn">Arşive ekle</button></div></div><div class="cards-list">${[...state.nights].sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<div class="surprise-card"><div class="row-between"><span class="chip">${fmtDate(x.date)}</span><button class="delete-btn" data-delnight="${x.id}">Sil</button></div><p>${escapeHtml(x.text)}</p></div>`).join('')||'<div class="empty">İlk iyi geceler mesajını ekle 🌙</div>'}</div>`;$('addNight').onclick=()=>{const text=$('nightText').value.trim();if(!text)return;state.nights.push({id:uid(),date:$('nightDate').value,text});save();renderNight();toast('Mesaj arşivlendi 🌙')};document.querySelectorAll('[data-delnight]').forEach(b=>b.onclick=()=>{state.nights=state.nights.filter(x=>x.id!=b.dataset.delnight);save();renderNight()})}

function renderEmergency(){$('moduleContent').innerHTML=`<div class="panel"><h3>Acil Necati hattı 🚨</h3><p class="muted">Bir butona basınca mesaj paylaşma ekranı açılır. Telefonda desteklenmiyorsa mesaj panoya kopyalanır.</p><div class="emergency-grid">${[['🤗','Sarılma lazım'],['🍫','Tatlı lazım'],['📞','Beni ara'],['❤️','İlgi lazım'],['☕','Kahve/çay'],['🚗','Gel beni al']].map(([e,t])=>`<button class="emergency-btn" data-emergency="${t}"><span>${e}</span>${t}</button>`).join('')}</div></div><div class="panel"><h3>Son çağrılar</h3>${state.emergencyLog.length?state.emergencyLog.slice(-5).reverse().map(x=>`<div class="surprise-card">${new Date(x.at).toLocaleString('tr-TR')} · ${escapeHtml(x.type)}</div>`).join(''):'<div class="empty">Henüz çağrı yok.</div>'}</div>`;document.querySelectorAll('[data-emergency]').forEach(b=>b.onclick=async()=>{const type=b.dataset.emergency,msg=`🚨 Necati Cepte çağrısı: ${state.settings.partnerName} diyor ki “${type}” ❤️`;state.emergencyLog.push({at:new Date().toISOString(),type});save();try{if(navigator.share)await navigator.share({title:'Necati Cepte',text:msg});else{await navigator.clipboard.writeText(msg);toast('Mesaj panoya kopyalandı ❤️')}}catch{}renderEmergency()})}

function renderBirthday(){const b=state.settings.birthDate;if(!b){$('moduleContent').innerHTML=`<div class="panel"><div class="empty">Nisa'nın doğum tarihini ⚙️ Ayarlar bölümünden gir. Sonra burası otomatik hesaplanacak 🎂</div></div>`;return}const birth=new Date(b+'T12:00:00'),now=new Date(),ms=now-birth,days=Math.floor(ms/86400000),weeks=Math.floor(days/7),months=(now.getFullYear()-birth.getFullYear())*12+(now.getMonth()-birth.getMonth()),years=now.getFullYear()-birth.getFullYear()-(new Date(now.getFullYear(),birth.getMonth(),birth.getDate())>now?1:0),weekday=birth.toLocaleDateString('tr-TR',{weekday:'long'});let next=new Date(now.getFullYear(),birth.getMonth(),birth.getDate());if(next<now)next.setFullYear(now.getFullYear()+1);const left=Math.ceil((next-now)/86400000);$('moduleContent').innerHTML=`<div class="panel"><span class="pill">${fmtDate(b)} 🎂</span><h3>${state.settings.partnerName}'nın dünyaya geldiği gün</h3><div class="stats-grid"><div class="stat-card"><strong>${weekday}</strong><span>Doğduğu gün</span></div><div class="stat-card"><strong>${years}</strong><span>Tamamlanan yaş</span></div><div class="stat-card"><strong>${days.toLocaleString('tr-TR')}</strong><span>Yaşadığı gün</span></div><div class="stat-card"><strong>${weeks.toLocaleString('tr-TR')}</strong><span>Yaklaşık hafta</span></div><div class="stat-card"><strong>${months.toLocaleString('tr-TR')}</strong><span>Takvim ayı</span></div><div class="stat-card"><strong>${left}</strong><span>Doğum gününe kalan gün</span></div></div></div>`}

$('settingsBtn').onclick=()=>{const s=state.settings;$('partnerName').value=s.partnerName;$('ownerName').value=s.ownerName;$('relationshipDate').value=s.relationshipDate;$('birthDate').value=s.birthDate;$('lastPeriod').value=s.lastPeriod;$('cycleLength').value=s.cycleLength;$('periodLength').value=s.periodLength;$('settingsDialog').showModal()};
$('settingsForm').addEventListener('close',()=>{});
$('settingsDialog').addEventListener('close',()=>{if($('settingsDialog').returnValue!=='save')return;state.settings={partnerName:$('partnerName').value.trim()||'Nisa',ownerName:$('ownerName').value.trim()||'Necati',relationshipDate:$('relationshipDate').value,birthDate:$('birthDate').value,lastPeriod:$('lastPeriod').value,cycleLength:+$('cycleLength').value||28,periodLength:+$('periodLength').value||5};save();updateIdentity();updateCounter();toast('Ayarlar kaydedildi ❤️')});
$('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='necati-cepte-yedek.json';a.click();URL.revokeObjectURL(a.href)};
$('importInput').onchange=e=>{const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{state=merge(defaultState,JSON.parse(r.result));save();updateIdentity();$('settingsDialog').close();toast('Yedek yüklendi ✅')}catch{toast('Geçersiz yedek dosyası')}};r.readAsText(file)};
$('randomLoveBtn').onclick=()=>{$('loveDialogText').textContent=`Seni seviyorum çünkü ${dailyJar()}.`;$('loveDialog').showModal()};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').hidden=false});$('installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBtn').hidden=true};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
